### ISSUE TITLE
GDPbyIndustry driver fails with TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by bertrandmarc** [jjotterson/datapungibea#3]
Dear datapungibea developper,

I could not manage to download any data from the GDPbyIndustry driver. For instance with the example from the doc:
```python
>>> data.GDPbyIndustry('211','1','A','2018')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\datapungibea\api.py", line 36, in wrapper
    return(getattr(delegate_object, called_method)(*args, **kwargs))
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\datapungibea\drivers.py", line 890, in GDPbyIndustry
    output       = self._cleanOutput(query,retrivedData) #a dict of a df or df and meta (tablePretty)
  File "C:\Users\marcber\PycharmProjects\venv\lib\site-packages\datapungibea\drivers.py", line 904, in _cleanOutput
    df_output =  pd.DataFrame(retrivedData.json()['BEAAPI']['Results']['Data'])
TypeError: list indices must be integers or slices, not str
```
Please note that the other drivers I tested work fine.

Best regards,
Bertrand

**Comment by jjotterson** [comment]
Hi Bertrand, thank you very much for pointing this out.  I guess BEA changed the API. jdretz's patch solves this problem - thanks a lot jdretz!  Closing this issue.
